# Generated by Django 2.1.3 on 2019-01-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passeport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=25)),
                ('description', models.TextField(max_length=100)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=5)),
                ('images', models.ImageField(default='static/images/pp.jpg', upload_to='static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='PorteCarte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=25)),
                ('description', models.TextField(max_length=100)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=5)),
                ('images', models.ImageField(default='static/images/pp.jpg', upload_to='static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='TehudaZehut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=25)),
                ('description', models.TextField(max_length=100)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=5)),
                ('images', models.ImageField(default='static/images/pp.jpg', upload_to='static/images/')),
            ],
        ),
    ]
